name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the library
        run: dotnet build --configuration Release --no-restore

      - name: Pack the NuGet package
        run: dotnet pack --configuration Release --no-build -o ./output

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./output/*.nupkg --source https://api.nuget.org/v3/index.json